### ISSUE TITLE
Help on Showing the Map

### ISSUE THREAD

**Issue by deybpors** [MauriceButler/godot-google-maps-plugin-android#1]
Hello! Thank you for this plugin. I have done everything for this to work. I have researched lots of videos for this to work on Godot 4. However, I could not get it to work. Debugging in Godot seems to not work and sends an error stating that mapPlugin is null. So I thought maybe when exporting to APK it will work. I also tried it to export in APK and run it on an emulator and it still wont work (the map is not showing on screen like in your GIF example.) I just would like to know how to make it to work :(

**Comment by MauriceButler** [comment]
The map plugin will always be `null` when running from godot, the plugin will only load when loaded on a device.

The way to debug it would be via deploying to a connected device or emulator with remote debugging enabled in godot. This page might help you to get that working https://docs.godotengine.org/en/stable/tutorials/export/one-click_deploy.html
![image](https://github.com/MauriceButler/godot-google-maps-plugin-android/assets/657135/c0fb0950-4f0c-4ddc-84c1-4245736ce4e2)

The only other thing I can think of to why it may not be appearing when you exported to an APK is maybe you have not enabled the location permissions in the export settings?
![image](https://github.com/MauriceButler/godot-google-maps-plugin-android/assets/657135/7f6eb36c-b2fe-4e5b-be65-9e8551cc5f13)
