### ISSUE TITLE
Problem with google map creation

### ISSUE THREAD

**Issue by Famouzy** [MauriceButler/godot-google-maps-plugin-android#2]
Good afternoon, I ran into a problem when porting your plugin to godot 4. The essence of the problem is that when starting the application at the moment of map creation (code attached) the application just crashes.
```

activity.runOnUiThread(() -> {
             FrameLayout.LayoutParams mapLayoutParams = new FrameLayout.LayoutParams(
                    FrameLayout.LayoutParams.MATCH_PARENT,
                     1000,
                     Gravity.BOTTOM
            );
 
             mapView = new MapView(activity); // this line shut down my app
 
             Bundle bundle = new Bundle();
             Bundle mapViewBundle = bundle.getBundle(googleMapsApiKey);
 
             mapView.onCreate(mapViewBundle);
 
             layout.addView(mapView, mapLayoutParams);
         });
```

Can u help me, please?

**Comment by MauriceButler** [comment]
Hi,

I have not actualy looked at this in Godot 4 since the Betas, so it is very possibly it does not work with the latest releases.

That being said, if thats the line of code that failing, thats java creating a Google MapView so should not be affected by different versions of Godot.

What could affect that is incorrect versions of the com.google.android.gms.maps.MapView libraries when compiled vs the target version of android you have selected in the export template.

**Comment by Famouzy** [comment]
> Hi,
> 
> I have not actualy looked at this in Godot 4 since the Betas, so it is very possibly it does not work with the latest releases.
> 
> That being said, if thats the line of code that failing, thats java creating a Google MapView so should not be affected by different versions of Godot.
> 
> What could affect that is incorrect versions of the com.google.android.gms.maps.MapView libraries when compiled vs the target version of android you have selected in the export template.

Thanks for the reply, the logs showed that the error is that the MapView class is missing

```
01-10 13:45:04.247  4185  4185 E AndroidRuntime: FATAL EXCEPTION: main
01-10 13:45:04.247  4185  4185 E AndroidRuntime: Process: org.godotengine.android.plugin.maps, PID: 4185
01-10 13:45:04.247  4185  4185 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/MapView;
```

**Comment by Famouzy** [comment]
problem was solved by copy all dependencies from plugin compilation to target export templates 
;\
